
namespace MTG.Enumerations
{
    public enum AbilityType
    {
        None,
        Deathtouch,
        Defender,
        Double_Strike,
        Enchant,
        Equip,
        First_Strike,
        Flash,
        Flying,
        Haste,
        Hexproof,
        Indestructible,
        Intimidate,
        Landwalk,
        Lifelink,
        Protection,
        Reach,
        Shroud,
        Trample,
        Vigilance,
        Banding,
        Rampage,
        Cumulative_Upkeep,
        Flanking,
        Phasing,
        Buyback,
        Shadow,
        Cycling,
        Echo,
        Horsemanship,
        Fading,
        Kicker,
        Flashback,
        Madness,
        Fear,
        Morph,
        Amplify,
        Provoke,
        Storm,
        Affinity,
        Entwine,
        Modular,
        Sunburst,
        Bushido,
        Soulshift,
        Splice,
        Offering,
        Ninjutsu,
        Epic,
        Convoke,
        Dredge,
        Transmute,
        Bloodthirst,
        Haunt,
        Replicate,
        Forecast,
        Graft,
        Recover,
        Ripple,
        Split_Second,
        Suspend,
        Vanishing,
        Absorb,
        Aura_Swap,
        Delve,
        Fortify,
        Frenzy,
        Gravestorm,
        Poisonous,
        Transfigure,
        Champion,
        Changeling,
        Evoke,
        Hideaway,
        Prowl,
        Reinforce,
        Conspire,
        Persist,
        Wither,
        Retrace,
        Devour,
        Exalted,
        Unearth,
        Cascade,
        Annihilator,
        Level_Up,
        Rebound,
        Totem_Armor,
        Infect,
        Battle_Cry,
        Living_Weapon,
        Undying,
        Miracle,
        Soulbond,
        Overload,
        Scavenge,
        Unleash,
        Cipher,
        Evolve,
        Extort,
        Fuse,
        Bestow,
        Tribute,
        Dethrone,
        Hidden_Agenda,
        Outlast,
        Prowess,
        Dash,
        Exploit,
        Menace,
        Renown,
        Awaken,
        Devoid,
        Ingest,
        Myriad,
        Surge,
        Skulk,
        Emerge,
        Escalate,
        Melee,
        Crew,
        Fabricate,
        Partner,
        Undaunted,
        Improvise,
        Aftermath,
        Embalm,
        Eternalize,
        Afflict,
        Ascend,
        Assist,
    }
    public enum CardType
    {
        None,
        Artifact,
        Creature,
        Enchantment,
        Instant,
        Land,
        Planeswalker,
        Sorcery,
        Tribal,
        Plane,
        Phenomena,
        Vanguard,
        Scheme,
        Conspiracy
    }
    public enum Colors
    {
        None,
        Black,
        Blue,
        Colorless,
        Green,
        Red,
        White
    }
    public enum EffectTypes
    {
        None,
        Destroy,
        Damage,
        DrawCard,
        DiscardCard,
        PlaceCardInLibrary_Top,
        PlaceCardInLibrary_Bottom,
        ShuffleLibrary,
        CombineGraveyardToLibrary,
        CombineHandToLibrary,
    }
    public enum GamePhases
    {
        None = 0,
        Beginning_Untap = 1,
        Beginning_Upkeep = 2,
        Beginning_Draw = 3,
        PreCombat_Main = 4,
        Combat_Beginning = 5,
        Combat_DeclareAttackers = 6,
        Combat_DeclareDefenders = 7,
        Combat_Damage = 8,
        Combat_Ending = 9,
        PostCombat_Main = 10,
        Ending_End = 11,
        Ending_Cleanup = 12
    }
    public enum GameType
    {
        None,
        Melee
    }
    public enum TargetScope
    {
        None,
        All,
        Single,
        Specified_Number,
    }
    public enum TargetType
    {
        None,
        Artifact,
        Creature,
        Land,
        Permanent,
        Player,
    }
    public enum UpkeepRequirementTypes
    {
        None,
        Sacrifice_Creature,
        Damage,
        Discard,
        Discard_Random
    }
    public enum UpkeepFailedRequirementResults
    {
        None,
        Sacrifice_Creature,
        Damage,
    }
    public enum UpkeepTriggers
    {
        None,
        All,
        Owner,
        Opponnent,
        Team
    }
}
